# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jupyter:
    build: ./jupyter
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="