# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: db
    image: fa/mysql:v0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./data/db:/var/lib/mysql"

  adminer:
    container_name: adminer
    image: fa/adminer:v0
    restart: always
    ports:
      - 8080:8080